apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: demo
  labels:
    app.kubernetes.io/name: demo-api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: demo-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
